### ISSUE TITLE
install-dynet.sh fails to find eigen

### ISSUE THREAD

**Issue by ghpu** [danielhers/tupa#1]
What happens 
============

CMake Error at cmake/FindEigen3.cmake:39 (file):
  file failed to open for reading (No such file or directory):

    tupa/dynet/build/eigen/Eigen/src/Core/util/Macros.h
Call Stack (most recent call first):
  cmake/FindEigen3.cmake:65 (_eigen3_check_version)
  CMakeLists.txt:170 (find_package)

Caused by
=========
install-dynet.sh contains :
cmake .. -DEIGEN3_INCLUDE_DIR=eigen -DPYTHON=`which python`

Solution
======

Replace install-dynet.sh cmake line by :
cmake .. -DEIGEN3_INCLUDE_DIR=../eigen -DPYTHON=`which python`

**Comment by danielhers** [comment]
Thanks, I'll be happy to merge a pull request 😀
