### ISSUE TITLE
Potential dependency conflicts between tupa and ucca

### ISSUE THREAD

**Issue by NeolithEra** [danielhers/tupa#101]
Hi, as shown in the following full dependency graph of **_tupa_**, **_tupa_** requires **_ucca <1.3,>=1.2.3_**, **_tupa_** requires **_semstr >=1.2.2,<1.3_** (**_semstr 1.2.2_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_semstr 1.2.2_** transitively introduces **_ucca >=1.2.3_**.

Obviously, there are multiple version constraints set for **_ucca_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_ucca 1.2.3_** (i.e., the newest version satisfying constraint **_<1.3,>=1.2.3_**) is the actually installed version.

Although the first found package version **_ucca 1.2.3_** just satisfies the later dependency constraint （**_ucca <1.3,>=1.2.3_**), such installed version is very close to the upper bound of the version constraint of ucca specified by **_semstr 1.2.2_**. 

Once **_semstr_** upgrades，its newest version will be installed, as **_tupa_** does not specify the upper bound of version constraint for **_semstr_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_semstr_** version introduces a higher version of **_ucca_**, violating its another version constraint **_<1.3,>=1.2.3_**.

According to the release history of semstr, it habitually upgrates Ucca in its recent releases. For instance, semstr 1.2.0 upgrated Ucca’s constraint from **_>=1.2.0 to >=1.2.1_**,semstr 1.2.1 upgrated Ucca’s constraint from **_>=1.2.1 to >=1.2.2_** and semstr 1.2.2 upgrated Ucca’s constraint from **_>=1.2.2 to >=1.2.3_**. 

As such, it is a warm warning of a potential dependency conflict issue for tupa.

### Dependency tree
```
tupa   - 1.4.2
| +- configargparse(install version:1.2.1 version range:>=0.14.0)
| +- cython(install version:3.0a1 version range:>=0.29)
| +- dynet(install version:2.1 version range:==2.1)
| +- logbook(install version:1.5.3 version range:>=1.5.2)
| +- numpy(install version:1.18.2 version range:>=1.15.0)
| +- semstr(install version:1.2.2 version range:>=1.2.2,<1.3)
| | +- configargparse(install version:1.2.1 version range:>=0.14.0)
| | +- numpy(install version:1.18.2 version range:>=1.15.0)  
| | +- requests(install version:2.23.0 version range:>=2.21.0)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| | +- tqdm(install version:4.45.0 version range:>=4.31.1)
| | +- ucca(install version:1.2.3 version range:>=1.2.3)
| +- tqdm(install version:4.45.0 version range:>=4.32.2)
| +- ucca(install version:1.2.3 version range:<1.3,>=1.2.3)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_ucca_** to be **_>=1.2.3_**.
2.	Remove your direct dependency **_ucca_**, and use the **_ucca_** transitively introduced by **_semstr_**.
3.	Change your direct dependency **_semstr_** to be **_<=1.2.2_**.
@danielhers Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by danielhers** [comment]
Thanks for the analysis.
semstr 1.2.x will always require ucca 1.2.x, and only semstr 1.3+ requires ucca 1.3+. I own both of them so I know that will be the case.
Therefore, I think the current situation is acceptable.
