### ISSUE TITLE
Error with English pre-trained model

### ISSUE THREAD

**Issue by feralvam** [danielhers/tupa#33]
Hello,
I downloaded the English pre-trained model, but when trying to unpack it I get the following error:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
I can train the parser (btw, the link to the Wiki corpus has changed), but I thought I should let you know.

**Comment by danielhers** [comment]
Thanks.
After downloading [the model](https://github.com/huji-nlp/tupa/releases/download/v1.3.2/ucca-bilstm-1.3.2.tar.gz), I ran `tar xvzf ucca-bilstm-1.3.2.tar.gz` and it extracted it successfully. Perhaps the file you downloaded is corrupted? Please try downloading it again.

**Comment by feralvam** [comment]
Hi!
I could download and then unpack it successfully using `wget`. If i download it using `curl` I still get the same error I mentioned when using `tar`. Anyway, thank you for the quick reply.
