### ISSUE TITLE
Train a multitask parser

### ISSUE THREAD

**Issue by baozuyi** [danielhers/tupa#55]
Hi,
Following the Readme, I can train the parser on Wiki-sentences. But I wonder how to train a multitask parser proposed in the paper of ACL2018. Thanks.

**Comment by danielhers** [comment]
Hi @baozuyi . To train a multitask model, simply pass directories/filenames of multiple formats to the `--train` argument. The supported formats are `.conllu`, `.sdp` and `.amr`. Let me know if it works or if you have more questions.

**Comment by danielhers** [comment]
Here is where you can get data for other formats:
* `.conllu`: https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-2895
* `.sdp`: http://sdp.delph-in.net/osdp-12.tgz
* `.amr`: https://amr.isi.edu/download.html

**Comment by danielhers** [comment]
It depends on your hardware, but with the full training data for all tasks it can take between 1 to 3 weeks to reach the best dev score.

**Comment by baozuyi** [comment]
Thanks @danielhers

**Comment by mcsuy** [comment]
Hi. I have a question regarding the amr files. Are the data files really meant to have .amr extensions? I ask this because the little prince corpus I downloaded was in txt format.

**Comment by danielhers** [comment]
You can just rename it to .amr and it will be recognized as AMR format. Since the format is recognized by the suffix, there's no way to distinguish between an AMR file and a plain text file otherwise...
