### ISSUE TITLE
How to parse multiple of text files in one time?

### ISSUE THREAD

**Issue by CarolLi** [danielhers/tupa#70]
The parser runs very slow using `python -m tupa example.txt -m <model_filename>` .  I think the reason is that the model `ucca-bilstm` needs to be loaded every time the command runs, and I have lots of files.  Therefore, is there a way that I could parse all my text files once the model loaded?

**Comment by danielhers** [comment]
Sure, you can pass as many text files as you like, or a directory of text files, or a glob pattern.

**Comment by CarolLi** [comment]
> Sure, you can pass as many text files as you like, or a directory of text files, or a glob pattern.

What command I can use to batch processing the files?  I think it is a waste to load a whole model for just parsing one file.

**Comment by danielhers** [comment]
If you want to parse `example1.txt`, `example2.txt` and `example3.txt`, use this command:

    python -m tupa example1.txt example2.txt example3.txt -m <model_filename>

Alternatively, you can run:

    python -m tupa example*.txt -m <model_filename>

Or if you have a directory `example_dir` with text files in it, run:

    python -m tupa example_dir -m <model_filename>

**Comment by CarolLi** [comment]
> If you want to parse `example1.txt`, `example2.txt` and `example3.txt`, use this command:
> 
> ```
> python -m tupa example1.txt example2.txt example3.txt -m <model_filename>
> ```
> 
> Alternatively, you can run:
> 
> ```
> python -m tupa example*.txt -m <model_filename>
> ```
> 
> Or if you have a directory `example_dir` with text files in it, run:
> 
> ```
> python -m tupa example_dir -m <model_filename>
> ```
> 
> Let me know if you have any more questions.

Thank you!  Another question about batch processing has raised just now.  If I have multiple directories of examples, how can I do the parsing at once?

**Comment by danielhers** [comment]
Same idea:

    python -m tupa example_dir1 example_dir2 -m <model_filename>

**Comment by CarolLi** [comment]
> Same idea:
> 
> ```
> python -m tupa example_dir1 example_dir2 -m <model_filename>
> ```

Thank you very much!
