### ISSUE TITLE
How can I train the parser using other corpus?

### ISSUE THREAD

**Issue by CarolLi** [danielhers/tupa#71]
I think the pre-trained model is too large for my task, therefore, I want to train the model using another corpus.  Is there any format requirements for the training data?

**Comment by danielhers** [comment]
Do you want to train it for UCCA parsing, or for parsing text to another representation?
If UCCA parsing, you can use any of the UCCA-annotated corpora: https://github.com/UniversalConceptualCognitiveAnnotation
It's best to use the sentence-split files, which are under the `master-sentences-xml` branch in each of these repositories:
https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-Wiki/tree/master-sentences-xml
https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/tree/master-sentences-xml
https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-20K/tree/master-sentences-xml
https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_German-20K/tree/master-sentences-xml
https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_French-20K/tree/master-sentences-xml

**Comment by CarolLi** [comment]
> Do you want to train it for UCCA parsing, or for parsing text to another representation?
> If UCCA parsing, you can use any of the UCCA-annotated corpora: https://github.com/UniversalConceptualCognitiveAnnotation
> It's best to use the sentence-split files, which are under the `master-sentences-xml` branch in each of these repositories:
> 
> * https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-Wiki/tree/master-sentences-xml
> * https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/tree/master-sentences-xml
> * https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-20K/tree/master-sentences-xml
> * https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_German-20K/tree/master-sentences-xml
> * https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_French-20K/tree/master-sentences-xml

Got it! Thank you~
