### ISSUE TITLE
How can I get the same output as in parser demo?

### ISSUE THREAD

**Issue by Zosia-Sham** [danielhers/tupa#73]
Hello.
Sorry if the question is stupid, I'm just starting to figure it out. I am using BiLSTM model pre-trained on the Wiki corpus. Demo and pre-trained model give slightly different output for same sentence. If I got it right, demo is based on an older BiLSTM model. Can I get the same output as in there?
Thank you

**Comment by danielhers** [comment]
Hi @Zosia-Sham, thanks for pointing it out -- the released pre-trained models are pretty old, and the demo is running a newer model. [Here](http://cs.huji.ac.il/~danielh/ucca/ucca-bilstm-spacy-20181122-gated-2.tar.gz) it is. I'll also upload newer models to the latest [release](https://github.com/huji-nlp/tupa/releases/tag/v1.3.9).
