### ISSUE TITLE
AMR Parser

### ISSUE THREAD

**Issue by MrAssis** [danielhers/tupa#93]
Does TUPA have any kind of Parser AMR? if yes, how do i use it?

**Comment by danielhers** [comment]
Yes, but I don't have a pre-trained model and haven't done a thorough evaluation. If you want to train your own, you are most welcome. Just give it AMR files and specify `--formats amr`.
If you want to parse to AMR in the [MRP JSON format](http://mrp.nlpl.eu/), you can use the pre-trained model [here](https://github.com/danielhers/tupa/releases) along with the code from the [mrp branch](https://github.com/danielhers/tupa/tree/mrp).
